version: '2'

volumes:
  data:
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    # volumes:
    #   - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    labels:
      - environment:development

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
    labels:
      - environment:development
